# Generated by Django 6.1.1 on 2026-09-04 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('day', models.IntegerField(choices=[(1, 'Jumatatu'), (2, 'Jumanne'), (3, 'Jumatano'), (4, 'Alhamisi'), (5, 'Ijumaa'), (6, 'Jumamosi'), (7, 'Jumapili')], unique=True, verbose_name='Siku')),
                ('opens_at', models.TimeField(blank=True, null=True, verbose_name='Kufungua')),
                ('closes_at', models.TimeField(blank=True, null=True, verbose_name='Kufunga')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Imefungwa siku hii')),
                ('note', models.CharField(blank=True, help_text='Mfano: Nusu siku, au Kwa miadi tu.', max_length=80, verbose_name='Maelezo')),
            ],
            options={
                'verbose_name': 'Saa za kazi',
                'verbose_name_plural': 'Saa za kazi',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_primary', models.CharField(blank=True, max_length=30, verbose_name='Simu ya kwanza')),
                ('phone_secondary', models.CharField(blank=True, max_length=30, verbose_name='Simu ya pili')),
                ('whatsapp', models.CharField(blank=True, help_text='Muundo wa kimataifa bila alama, mfano 255628601130', max_length=30, verbose_name='Namba ya WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email kuu')),
                ('email_sales', models.EmailField(blank=True, max_length=254, verbose_name='Email ya mauzo')),
                ('street', models.CharField(blank=True, max_length=160, verbose_name='Mtaa / jengo')),
                ('ward', models.CharField(blank=True, default='Kigamboni', max_length=80, verbose_name='Kata')),
                ('city', models.CharField(blank=True, default='Dar es Salaam', max_length=80, verbose_name='Jiji')),
                ('postal_address', models.CharField(blank=True, max_length=80, verbose_name='S.L.P')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Mawasiliano',
                'verbose_name_plural': 'Mawasiliano',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('question', models.CharField(max_length=200, verbose_name='Swali')),
                ('answer', models.TextField(verbose_name='Jibu')),
            ],
            options={
                'verbose_name': 'Swali la mara kwa mara',
                'verbose_name_plural': 'Maswali ya mara kwa mara',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('headline', models.CharField(max_length=90, verbose_name='Kichwa kikubwa')),
                ('subline', models.CharField(blank=True, max_length=180, verbose_name='Maelezo ya chini')),
                ('image', models.ImageField(help_text='Upana wa angalau 2000px, ubora mzuri.', upload_to='hero/', verbose_name='Picha')),
                ('cta_label', models.CharField(blank=True, max_length=40, verbose_name='Maandishi ya kitufe')),
                ('cta_url', models.CharField(blank=True, max_length=200, verbose_name='Link ya kitufe')),
            ],
            options={
                'verbose_name': 'Slide ya homepage',
                'verbose_name_plural': 'Slides za homepage',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Kinachoonekana Google. Ukikiacha wazi, jina la kawaida litatumika.', max_length=70, verbose_name='Kichwa cha SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Sentensi 1-2 zinazoonekana chini ya kichwa kwenye Google.', max_length=160, verbose_name='Maelezo ya SEO')),
                ('og_image', models.ImageField(blank=True, help_text='Inayoonekana link ikishirikishwa WhatsApp au Facebook. 1200x630px.', upload_to='seo/', verbose_name='Picha ya kushare')),
                ('title', models.CharField(max_length=120, verbose_name='Kichwa')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('body', models.TextField(verbose_name='Maandishi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana')),
            ],
            options={
                'verbose_name': 'Ukurasa',
                'verbose_name_plural': 'Kurasa',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Kinachoonekana Google. Ukikiacha wazi, jina la kawaida litatumika.', max_length=70, verbose_name='Kichwa cha SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Sentensi 1-2 zinazoonekana chini ya kichwa kwenye Google.', max_length=160, verbose_name='Maelezo ya SEO')),
                ('og_image', models.ImageField(blank=True, help_text='Inayoonekana link ikishirikishwa WhatsApp au Facebook. 1200x630px.', upload_to='seo/', verbose_name='Picha ya kushare')),
                ('company_name', models.CharField(default='AMISH Company Limited', max_length=120, verbose_name='Jina la kampuni')),
                ('slogan', models.CharField(default='Your Success, Our Commitment', max_length=160, verbose_name='Slogan')),
                ('short_intro', models.TextField(blank=True, help_text='Sentensi 2-3 zinazoelezea kampuni. Zinatumika footer na sehemu za utangulizi.', verbose_name='Utangulizi mfupi')),
                ('logo', models.ImageField(blank=True, upload_to='brand/', verbose_name='Logo (background nyeupe)')),
                ('logo_light', models.ImageField(blank=True, upload_to='brand/', verbose_name='Logo ya background nyeusi')),
                ('favicon', models.ImageField(blank=True, help_text='Alama ndogo ya browser tab. 512x512px.', upload_to='brand/', verbose_name='Favicon')),
                ('color_primary', models.CharField(default='#142B6F', max_length=7, verbose_name='Rangi kuu (dark blue)')),
                ('color_ink', models.CharField(default='#000000', max_length=7, verbose_name='Rangi ya maandishi (black)')),
                ('color_surface', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Rangi ya background (white)')),
            ],
            options={
                'verbose_name': 'Mipangilio ya website',
                'verbose_name_plural': 'Mipangilio ya website',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('value', models.CharField(help_text='Mfano: 12, 500+, 98%', max_length=20, verbose_name='Namba')),
                ('label', models.CharField(help_text='Mfano: Miaka ya uzoefu', max_length=60, verbose_name='Maelezo')),
            ],
            options={
                'verbose_name': 'Takwimu',
                'verbose_name_plural': 'Takwimu',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('author', models.CharField(max_length=90, verbose_name='Jina la mteja')),
                ('role', models.CharField(blank=True, max_length=90, verbose_name='Cheo au kampuni')),
                ('quote', models.TextField(verbose_name='Alichosema')),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Picha')),
            ],
            options={
                'verbose_name': 'Ushuhuda wa mteja',
                'verbose_name_plural': 'Ushuhuda wa wateja',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=90, verbose_name='Jina')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Simu')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=140, verbose_name='Mada')),
                ('message', models.TextField(verbose_name='Ujumbe')),
                ('status', models.CharField(choices=[('new', 'Mpya'), ('in_progress', 'Inashughulikiwa'), ('closed', 'Imekamilika')], default='new', max_length=20, verbose_name='Hali')),
                ('internal_note', models.TextField(blank=True, verbose_name='Maelezo ya ndani')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='divisions.division', verbose_name='Idara husika')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='divisions.product', verbose_name='Bidhaa husika')),
            ],
            options={
                'verbose_name': 'Ujumbe wa mteja',
                'verbose_name_plural': 'Ujumbe wa wateja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('whatsapp_channel', 'WhatsApp Channel'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('x', 'X (Twitter)')], max_length=30, verbose_name='Platform')),
                ('handle', models.CharField(blank=True, help_text='Mfano: AMISH Hardware', max_length=80, verbose_name='Jina la page')),
                ('url', models.URLField(verbose_name='Link')),
                ('division', models.ForeignKey(blank=True, help_text='Iache wazi kama ni page ya kampuni nzima.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_links', to='divisions.division', verbose_name='Ni ya idara gani')),
            ],
            options={
                'verbose_name': 'Link ya social media',
                'verbose_name_plural': 'Links za social media',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
