# Generated by Django 6.1.1 on 2026-09-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('slot', models.CharField(choices=[('band', 'Ukanda wa Vision na Mission')], default='band', max_length=20, verbose_name='Sehemu')),
                ('image', models.ImageField(upload_to='sections/', verbose_name='Picha')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='Maelezo ya ndani')),
            ],
            options={
                'verbose_name': 'Picha ya nyuma',
                'verbose_name_plural': 'Picha za nyuma',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
