# Generated by Django 6.1.1 on 2026-09-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sectionslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('title', models.CharField(max_length=70, verbose_name='Kichwa')),
                ('description', models.TextField(verbose_name='Maelezo')),
            ],
            options={
                'verbose_name': 'Sababu ya kununua hapa',
                'verbose_name_plural': 'Kwa nini AMISH',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
