# Generated by Django 5.2.17 on 2026-09-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionslide',
            name='slot',
            field=models.CharField(choices=[('band', 'Ukanda wa Vision na Mission'), ('footer', 'Nyuma ya footer')], default='band', max_length=20, verbose_name='Sehemu'),
        ),
    ]
