# Generated by Django 5.2.17 on 2026-09-06 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sectionslide_slot'),
        ('divisions', '0003_alter_category_options_alter_division_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesshour',
            options={'ordering': ['day'], 'verbose_name': 'Opening hours', 'verbose_name_plural': 'Opening hours'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact details', 'verbose_name_plural': 'Contact details'},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer enquiry', 'verbose_name_plural': 'Customer enquiries'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', 'id'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Home page slide', 'verbose_name_plural': 'Home page slides'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='reason',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Reason to buy here', 'verbose_name_plural': 'Why AMISH'},
        ),
        migrations.AlterModelOptions(
            name='sectionslide',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Background image', 'verbose_name_plural': 'Background images'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site settings', 'verbose_name_plural': 'Site settings'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Social media link', 'verbose_name_plural': 'Social media links'},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Key figure', 'verbose_name_plural': 'Key figures'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='closes_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Closes at'),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Closed on this day'),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='note',
            field=models.CharField(blank=True, help_text='For example: Half day, or By appointment only.', max_length=80, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='opens_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Opens at'),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='city',
            field=models.CharField(blank=True, default='Dar es Salaam', max_length=80, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Main email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email_sales',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Sales email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=30, verbose_name='Primary phone'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=30, verbose_name='Second phone'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='postal_address',
            field=models.CharField(blank=True, max_length=80, verbose_name='P.O. Box'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='street',
            field=models.CharField(blank=True, max_length=160, verbose_name='Street or building'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='ward',
            field=models.CharField(blank=True, default='Kigamboni', max_length=80, verbose_name='Ward'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='International format with no symbols, for example 255711686816', max_length=30, verbose_name='WhatsApp number'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='divisions.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='internal_note',
            field=models.TextField(blank=True, verbose_name='Internal note'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=90, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='divisions.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(blank=True, max_length=140, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_label',
            field=models.CharField(blank=True, max_length=40, verbose_name='Button label'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Button link'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='headline',
            field=models.CharField(max_length=90, verbose_name='Headline'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='At least 2000px wide, good quality.', upload_to='hero/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subline',
            field=models.CharField(blank=True, max_length=180, verbose_name='Supporting text'),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(verbose_name='Body text'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, help_text='One or two sentences shown under the title in Google.', max_length=160, verbose_name='SEO description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Shown in Google results. Leave blank to use the normal title.', max_length=70, verbose_name='SEO title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Shown when the link is shared on WhatsApp or Facebook. 1200x630px.', upload_to='seo/', verbose_name='Share image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sectionslide',
            name='caption',
            field=models.CharField(blank=True, max_length=120, verbose_name='Internal note'),
        ),
        migrations.AlterField(
            model_name='sectionslide',
            name='image',
            field=models.ImageField(upload_to='sections/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='sectionslide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='sectionslide',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='sectionslide',
            name='slot',
            field=models.CharField(choices=[('band', 'Vision and Mission band'), ('footer', 'Footer background')], default='band', max_length=20, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_ink',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Text colour'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_primary',
            field=models.CharField(default='#142B6F', max_length=7, verbose_name='Primary colour'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_surface',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Background colour'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='AMISH Company Limited', max_length=120, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Small icon shown in the browser tab. 512x512px.', upload_to='brand/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='brand/', verbose_name='Logo (for light backgrounds)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_light',
            field=models.ImageField(blank=True, upload_to='brand/', verbose_name='Logo (for dark backgrounds)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, help_text='One or two sentences shown under the title in Google.', max_length=160, verbose_name='SEO description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Shown in Google results. Leave blank to use the normal title.', max_length=70, verbose_name='SEO title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Shown when the link is shared on WhatsApp or Facebook. 1200x630px.', upload_to='seo/', verbose_name='Share image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='short_intro',
            field=models.TextField(blank=True, help_text='Two or three sentences describing the company. Used in the footer and intro sections.', verbose_name='Short introduction'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this is a company-wide page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_links', to='divisions.division', verbose_name='Which division'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='handle',
            field=models.CharField(blank=True, help_text='For example: AMISH Hardware', max_length=80, verbose_name='Page name'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='label',
            field=models.CharField(help_text='For example: Years of experience', max_length=60, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='value',
            field=models.CharField(help_text='For example: 12, 500+, 98%', max_length=20, verbose_name='Figure'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author',
            field=models.CharField(max_length=90, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.TextField(verbose_name='What they said'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, max_length=90, verbose_name='Role or company'),
        ),
    ]
