# Generated by Django 6.1.1 on 2026-09-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Kinachoonekana Google. Ukikiacha wazi, jina la kawaida litatumika.', max_length=70, verbose_name='Kichwa cha SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Sentensi 1-2 zinazoonekana chini ya kichwa kwenye Google.', max_length=160, verbose_name='Maelezo ya SEO')),
                ('og_image', models.ImageField(blank=True, help_text='Inayoonekana link ikishirikishwa WhatsApp au Facebook. 1200x630px.', upload_to='seo/', verbose_name='Picha ya kushare')),
                ('intro', models.TextField(blank=True, help_text='Aya moja au mbili za kuanzia ukurasa wa About.', verbose_name='Utangulizi')),
                ('story', models.TextField(blank=True, verbose_name='Historia ya kampuni')),
                ('story_image', models.ImageField(blank=True, upload_to='about/', verbose_name='Picha')),
                ('vision_en', models.TextField(blank=True, verbose_name='Vision (English)')),
                ('vision_sw', models.TextField(blank=True, verbose_name='Vision (Kiswahili)')),
                ('mission_en', models.TextField(blank=True, verbose_name='Mission (English)')),
                ('mission_sw', models.TextField(blank=True, verbose_name='Mission (Kiswahili)')),
            ],
            options={
                'verbose_name': 'Kuhusu kampuni',
                'verbose_name_plural': 'Kuhusu kampuni',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('name', models.CharField(max_length=120, verbose_name='Jina la mteja')),
                ('logo', models.ImageField(blank=True, upload_to='clients/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Mteja au mshirika',
                'verbose_name_plural': 'Wateja na washirika',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('title', models.CharField(help_text='Mfano: Integrity, Accountability.', max_length=60, verbose_name='Thamani')),
                ('description', models.TextField(verbose_name='Maelezo')),
                ('icon', models.ImageField(blank=True, upload_to='values/', verbose_name='Ikoni')),
            ],
            options={
                'verbose_name': 'Thamani ya kampuni',
                'verbose_name_plural': 'Thamani za kampuni',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('kind', models.CharField(choices=[('registration', 'Usajili (BRELA)'), ('tin', 'TIN'), ('licence', 'Leseni'), ('certificate', 'Cheti')], max_length=20, verbose_name='Aina')),
                ('label', models.CharField(max_length=90, verbose_name='Jina')),
                ('number', models.CharField(blank=True, max_length=60, verbose_name='Namba')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='Ilitolewa tarehe')),
                ('document', models.FileField(blank=True, upload_to='credentials/', verbose_name='Faili')),
                ('show_on_website', models.BooleanField(default=False, help_text='Namba za usajili mara nyingi huwekwa footer tu.', verbose_name='Ionekane kwenye website')),
            ],
            options={
                'verbose_name': 'Cheti au usajili',
                'verbose_name_plural': 'Vyeti na usajili',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('year', models.CharField(max_length=12, verbose_name='Mwaka')),
                ('title', models.CharField(max_length=120, verbose_name='Kilichotokea')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo')),
            ],
            options={
                'verbose_name': 'Hatua ya kihistoria',
                'verbose_name_plural': 'Historia kwa miaka',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('full_name', models.CharField(max_length=120, verbose_name='Jina kamili')),
                ('position', models.CharField(max_length=90, verbose_name='Cheo')),
                ('bio', models.TextField(blank=True, verbose_name='Wasifu mfupi')),
                ('photo', models.ImageField(blank=True, upload_to='team/', verbose_name='Picha')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Simu')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('is_director', models.BooleanField(default=False, verbose_name='Ni mkurugenzi')),
                ('show_on_website', models.BooleanField(default=True, verbose_name='Aonekane kwenye website')),
                ('on_business_card', models.BooleanField(default=False, verbose_name='Ana business card')),
            ],
            options={
                'verbose_name': 'Mtu wa kampuni',
                'verbose_name_plural': 'Timu na wakurugenzi',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
