# Generated by Django 5.2.17 on 2026-09-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About the company', 'verbose_name_plural': 'About the company'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Client or partner', 'verbose_name_plural': 'Clients and partners'},
        ),
        migrations.AlterModelOptions(
            name='corevalue',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Core value', 'verbose_name_plural': 'Core values'},
        ),
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Registration or certificate', 'verbose_name_plural': 'Registration and certificates'},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Milestone', 'verbose_name_plural': 'Milestones'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Person', 'verbose_name_plural': 'Team and directors'},
        ),
        migrations.AlterField(
            model_name='about',
            name='intro',
            field=models.TextField(blank=True, help_text='One or two opening paragraphs for the About page.', verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='about',
            name='meta_description',
            field=models.CharField(blank=True, help_text='One or two sentences shown under the title in Google.', max_length=160, verbose_name='SEO description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Shown in Google results. Leave blank to use the normal title.', max_length=70, verbose_name='SEO title'),
        ),
        migrations.AlterField(
            model_name='about',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Shown when the link is shared on WhatsApp or Facebook. 1200x630px.', upload_to='seo/', verbose_name='Share image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='story',
            field=models.TextField(blank=True, verbose_name='Company story'),
        ),
        migrations.AlterField(
            model_name='about',
            name='story_image',
            field=models.ImageField(blank=True, upload_to='about/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Client name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='icon',
            field=models.ImageField(blank=True, upload_to='values/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='title',
            field=models.CharField(help_text='For example: Integrity, Accountability.', max_length=60, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='document',
            field=models.FileField(blank=True, upload_to='credentials/', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='issued_on',
            field=models.DateField(blank=True, null=True, verbose_name='Issued on'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='kind',
            field=models.CharField(choices=[('registration', 'Business registration (BRELA)'), ('tin', 'TIN'), ('licence', 'Licence'), ('certificate', 'Certificate')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='label',
            field=models.CharField(max_length=90, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='number',
            field=models.CharField(blank=True, max_length=60, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='show_on_website',
            field=models.BooleanField(default=False, help_text='Registration numbers are usually shown in the footer only.', verbose_name='Show on the website'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='title',
            field=models.CharField(max_length=120, verbose_name='What happened'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='year',
            field=models.CharField(max_length=12, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Short biography'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_director',
            field=models.BooleanField(default=False, verbose_name='Is a director'),
        ),
        migrations.AlterField(
            model_name='person',
            name='on_business_card',
            field=models.BooleanField(default=False, verbose_name='Has a business card'),
        ),
        migrations.AlterField(
            model_name='person',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='team/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(max_length=90, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='person',
            name='show_on_website',
            field=models.BooleanField(default=True, verbose_name='Show on the website'),
        ),
    ]
