# Generated by Django 6.1.1 on 2026-09-04 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('meta_title', models.CharField(blank=True, help_text='Kinachoonekana Google. Ukikiacha wazi, jina la kawaida litatumika.', max_length=70, verbose_name='Kichwa cha SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Sentensi 1-2 zinazoonekana chini ya kichwa kwenye Google.', max_length=160, verbose_name='Maelezo ya SEO')),
                ('og_image', models.ImageField(blank=True, help_text='Inayoonekana link ikishirikishwa WhatsApp au Facebook. 1200x630px.', upload_to='seo/', verbose_name='Picha ya kushare')),
                ('name', models.CharField(max_length=90, verbose_name='Jina la tawi')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Mfano: Vifaa vya ujenzi vya kuaminika kwa bei ya jumla.', max_length=140, verbose_name='Maelezo ya mstari mmoja')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo kamili')),
                ('status', models.CharField(choices=[('active', 'Inafanya kazi'), ('coming_soon', 'Inakuja hivi karibuni')], default='active', help_text="Ikiwa 'inakuja', tawi linaonekana lakini bidhaa zake hazionyeshwi.", max_length=20, verbose_name='Hali')),
                ('kind', models.CharField(choices=[('products', 'Inauza bidhaa'), ('services', 'Inatoa huduma')], default='products', max_length=20, verbose_name='Aina')),
                ('launch_note', models.CharField(blank=True, help_text='Kinachoonekana kwenye tawi linalokuja. Mfano: Inatarajiwa 2027.', max_length=90, verbose_name='Lini linaanza')),
                ('icon', models.ImageField(blank=True, upload_to='divisions/icons/', verbose_name='Ikoni')),
                ('cover', models.ImageField(blank=True, help_text='Inayoonekana juu ya ukurasa wa tawi. Upana wa angalau 1600px.', upload_to='divisions/', verbose_name='Picha kubwa')),
                ('accent_color', models.CharField(blank=True, help_text='Iache wazi ili itumie rangi kuu ya kampuni.', max_length=7, verbose_name='Rangi ya tawi')),
            ],
            options={
                'verbose_name': 'Tawi la kampuni',
                'verbose_name_plural': 'Matawi ya kampuni',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('name', models.CharField(max_length=90, verbose_name='Jina la kundi')),
                ('slug', models.SlugField(blank=True, max_length=110)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Maelezo mafupi')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Picha')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='divisions.division', verbose_name='Tawi')),
            ],
            options={
                'verbose_name': 'Kundi la bidhaa',
                'verbose_name_plural': 'Makundi ya bidhaa',
                'ordering': ['order', 'id'],
                'abstract': False,
                'unique_together': {('division', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Picha')),
                ('caption', models.CharField(blank=True, max_length=140, verbose_name='Maelezo')),
                ('division', models.ForeignKey(blank=True, help_text='Iache wazi kama ni picha ya kampuni kwa ujumla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='divisions.division', verbose_name='Tawi')),
            ],
            options={
                'verbose_name': 'Picha ya gallery',
                'verbose_name_plural': 'Gallery',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('meta_title', models.CharField(blank=True, help_text='Kinachoonekana Google. Ukikiacha wazi, jina la kawaida litatumika.', max_length=70, verbose_name='Kichwa cha SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Sentensi 1-2 zinazoonekana chini ya kichwa kwenye Google.', max_length=160, verbose_name='Maelezo ya SEO')),
                ('og_image', models.ImageField(blank=True, help_text='Inayoonekana link ikishirikishwa WhatsApp au Facebook. 1200x630px.', upload_to='seo/', verbose_name='Picha ya kushare')),
                ('name', models.CharField(max_length=140, verbose_name='Jina la bidhaa')),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='Maelezo mafupi')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo kamili')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Picha kuu')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bei (TSh)')),
                ('show_price', models.BooleanField(default=False, help_text='Ikizimwa, mteja anaona kitufe cha kuuliza bei badala ya namba.', verbose_name='Onyesha bei kwenye website')),
                ('unit', models.CharField(blank=True, help_text='Mfano: kwa mfuko, kwa mita, kwa kipande.', max_length=30, verbose_name='Kipimo')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Ipo dukani')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Ionekane homepage')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='divisions.category', verbose_name='Kundi')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='divisions.division', verbose_name='Tawi')),
            ],
            options={
                'verbose_name': 'Bidhaa',
                'verbose_name_plural': 'Bidhaa',
                'ordering': ['order', 'id'],
                'abstract': False,
                'unique_together': {('division', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Picha')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='Maelezo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='divisions.product', verbose_name='Bidhaa')),
            ],
            options={
                'verbose_name': 'Picha ya ziada',
                'verbose_name_plural': 'Picha za ziada',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('name', models.CharField(max_length=120, verbose_name='Jina la huduma')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='Maelezo mafupi')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo kamili')),
                ('icon', models.ImageField(blank=True, upload_to='services/', verbose_name='Ikoni')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='divisions.division', verbose_name='Tawi')),
            ],
            options={
                'verbose_name': 'Huduma',
                'verbose_name_plural': 'Huduma',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
