# Generated by Django 6.1.1 on 2026-09-04 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Namba ndogo inaonekana kwanza.', verbose_name='Mpangilio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inaonekana kwenye website')),
                ('image', models.ImageField(upload_to='divisions/slides/', verbose_name='Picha')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='Maelezo')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='divisions.division', verbose_name='Tawi')),
            ],
            options={
                'verbose_name': 'Picha ya paneli',
                'verbose_name_plural': 'Picha za paneli',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
