# Generated by Django 5.2.17 on 2026-09-06 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0002_divisionimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
        migrations.AlterModelOptions(
            name='divisionimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Panel photo', 'verbose_name_plural': 'Panel photos'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Gallery photo', 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Extra photo', 'verbose_name_plural': 'Extra photos'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='divisions.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=90, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='division',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Leave blank to use the company primary colour.', max_length=7, verbose_name='Division colour'),
        ),
        migrations.AlterField(
            model_name='division',
            name='cover',
            field=models.ImageField(blank=True, help_text='Shown at the top of the division page. At least 1600px wide.', upload_to='divisions/', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='division',
            name='description',
            field=models.TextField(blank=True, verbose_name='Full description'),
        ),
        migrations.AlterField(
            model_name='division',
            name='icon',
            field=models.ImageField(blank=True, upload_to='divisions/icons/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='division',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='division',
            name='kind',
            field=models.CharField(choices=[('products', 'Sells products'), ('services', 'Provides services')], default='products', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='division',
            name='launch_note',
            field=models.CharField(blank=True, help_text='Shown on a division in preparation. For example: Expected 2027.', max_length=90, verbose_name='Launch note'),
        ),
        migrations.AlterField(
            model_name='division',
            name='meta_description',
            field=models.CharField(blank=True, help_text='One or two sentences shown under the title in Google.', max_length=160, verbose_name='SEO description'),
        ),
        migrations.AlterField(
            model_name='division',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Shown in Google results. Leave blank to use the normal title.', max_length=70, verbose_name='SEO title'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=90, verbose_name='Division name'),
        ),
        migrations.AlterField(
            model_name='division',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Shown when the link is shared on WhatsApp or Facebook. 1200x630px.', upload_to='seo/', verbose_name='Share image'),
        ),
        migrations.AlterField(
            model_name='division',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='division',
            name='status',
            field=models.CharField(choices=[('active', 'Trading'), ('coming_soon', 'In preparation')], default='active', help_text="If set to 'In preparation', the division is listed but its products are hidden.", max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='division',
            name='tagline',
            field=models.CharField(blank=True, help_text='For example: Reliable building materials at wholesale prices.', max_length=140, verbose_name='One-line description'),
        ),
        migrations.AlterField(
            model_name='divisionimage',
            name='caption',
            field=models.CharField(blank=True, max_length=120, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='divisionimage',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='divisions.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='divisionimage',
            name='image',
            field=models.ImageField(upload_to='divisions/slides/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='divisionimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='divisionimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=140, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Iache wazi kama ni picha ya kampuni kwa ujumla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='divisions.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='divisions.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Full description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='divisions.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Main photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='In stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Feature on the home page'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='One or two sentences shown under the title in Google.', max_length=160, verbose_name='SEO description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Shown in Google results. Leave blank to use the normal title.', max_length=70, verbose_name='SEO title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Shown when the link is shared on WhatsApp or Facebook. 1200x630px.', upload_to='seo/', verbose_name='Share image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price (TSh)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_price',
            field=models.BooleanField(default=False, help_text="When off, customers see an 'Ask for price' link instead of a figure.", verbose_name='Show price on the website'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.CharField(blank=True, max_length=200, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, help_text='For example: per bag, per metre, per piece.', max_length=30, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, max_length=120, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='divisions.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Full description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='divisions.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, upload_to='services/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on the website'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Service name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='service',
            name='summary',
            field=models.CharField(blank=True, max_length=200, verbose_name='Short description'),
        ),
    ]
